### ISSUE TITLE
"iOS: There was an error with this build. Please try again."

### ISSUE THREAD

**Issue by lyahdav** [expo/exp#36]
I was following the directions [here](https://docs.getexponent.com/versions/v13.0.0/guides/building-standalone-apps.html#building-standalone-apps) to submit my Exponent app to the App Store and when I ran `exp build:status` I got the following output:

```
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] iOS: There was an error with this build. Please try again.
```

Here's the output from the `exp build:ios` command I ran before that:
```
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...
[exp] Validating Apple credentials...
[exp] Credentials valid.
[exp] Validating distribution certificate...
[exp] Validating app id...
[exp] Validating push certificate...
[exp] Starting build process...
[exp] Publishing...
[exp] Published
[exp] Your URL is

...
[exp] Building...
[exp] Build successfully started, it may take a few minutes to complete. Run "exp build:status" to monitor it.
```

Any ideas? I feel like when I first entered my Apple Team ID I put it in incorrectly but I would expect it not to say `Credentials valid` above if that were the case. Is there a way to make it forget my Apple credentials to try again?

**Comment by dikaiosune** [comment]
@lyahdav did the build error when running `exp build:status` subsequently? Unfortunately we don't currently validate team IDs before running the build -- incorrect team IDs will error during the build.

You can clear the credentials by running `exp build:ios -c` once the previous build has failed. Note that you may need to revoke certificates in the developer portal b/c this may try to create more than the 2-per-individual-account limit.

We're working on doing more validation for this data, and also exposing more information about build failures and logs to users during the process -- the current state of these is not great.

Let me know if running `exp build:ios -c` resolves your issue?

**Comment by lyahdav** [comment]
`exp build:ios -c` resolved it. Could you maybe add a note about this to the documentation if it will take a while to add the additional validation and error messaging?

**Comment by michaltaberski** [comment]
Hmm...

I got the same error message.

`exp build:ios` went just fine and by the end of its output I have message:

```
[exp] Building...
[exp] Build successfully started, it may take a few minutes to complete. Run "exp build:status" to monitor it.
```

however after I run `exp build:status` I am getting: (there is some time when the build is in progress, but sooner or later it fails).

```
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] iOS: There was an error with this build. Please try again.
```

Is there somewhere some detailed stacktrace, or how can I know whats the issue?

Thanks

**Comment by dikaiosune** [comment]
@michaltaberski can you try again? I believe there was an issue with the iOS builders that has since been resolved.

**Comment by michaltaberski** [comment]
@dikaiosune Yes, I can confirm. Now the build works well. Thanks a lot.

**Comment by rrecuero** [comment]
I get the same error as @michaltaberski. Is this happening again? A regression?

**Comment by michaltaberski** [comment]
@rrecuero I don't think it's regression. The problem is that expo does not provided a detailed error logs, so you don't know what is exactly the problem. There might be a bunch of different reasons. Best way to handle that is to visit expo channel on slack.

**Comment by brentvatne** [comment]
@dikaiosune is working hard on improving the build process, but as @michaltaberski said, feel free to join our Slack (slack.expo.io) and ping us to look into the issue for you if you have any problems!

**Comment by javidjamae** [comment]
Same issue here. No logs / messages describing the error makes it really hard to know why it failed.

**Comment by brentvatne** [comment]
@javidjamae - we are working on it, ping us on slack when you run into issues and we will look into them asap

**Comment by davidroman0O** [comment]
@brentvatne Same thing, i tried -c many times! And did the process for the p12 multiple times too...
I really don't know how to resolve this!
Build ID: 105545ae-0117-426f-a181-9664adfdd112

If you have any informations to resolve this issue, could be great! :p

**Comment by ide** [comment]
We can look into this for you tomorrow. Currently our standalone app builders are best supported Mon-Fri Pacific time.

**Comment by francocorreasosa** [comment]
I have a build error too on Android after I added Google Maps API keys in the `app.json` file. No error details are provided by expo.

**Comment by dikaiosune** [comment]
@davidroman0O it looks like your p12 file isn't validating correctly: `pkcs12: expected exactly two safe bags in the PFX PDU`. Make sure you're exporting a p12 that includes exactly the public cert and private key. It's usually much easier to let us make the certs for you.

@francocorreasosa can you post in our forums with your build ID? forums.expo.io

**Comment by pavinod** [comment]
I am getting the same error too! I am trying to publish my app to the App store. My build ID is 07d42ef5-8f79-4495-a618-a6d43b454d56 
Hope someone can help! Thanks

**Comment by francocorreasosa** [comment]
@dikaiosune My problem was solved _auto-magically™_. thanks anyways.

**Comment by dshaw002** [comment]
Any idea when you'll provide build error feedback on the CLI?

I'm having a problem and checking with slack.. my build ID is: 0202efa2-9f50-4685-95c0-f9389ef90317

If anything I'll copy my work into a regular RN project. I thought with 0 issues a project wouldn't have these type of problems.

**Comment by jengjeng** [comment]
I have fixed this issue by resizing&crop the app images/icons to square ratio.
(From [Expo Doc](https://docs.expo.io/versions/latest/guides/configuration.html#icon) that show we can't use an image as the icon above size 512x512 px.)

So, about the size of my images.
e.g.
> assets/icons/app-icon.png => 512x512 px
> assets/icons/loading-icon.png => 500x500 px
> assets/icons/notification-icon.png => 144x144 px

**Comment by HerbertLim** [comment]
As @jengjeng  said, unless icon's ratio is 1:1, build fails.
Thanks @jengjeng. 
I succeeded iOS build by changing icon image to 1024x1024 px, which is too large for icon but that was the only square logo image I got at the moment.

**Comment by Inlesco** [comment]
i'm getting the same generic `there was an error...` message.

Anybody know where to find the error logs of `exp build:ios -c` for debugging?

Also, i've tried to generate the required image assets for the iOS app following this - https://stackoverflow.com/a/40534324/7867018 - the images are generated in `root/ios/[appName]/images.xcassets/Appicon.appiconset/`, but... It did NOT solve the issue, sadly.

**Comment by brentvatne** [comment]
@Inlesco - working on streaming logs for this now, let us know your build id and we can help you debug the issue. sorry for the hassle!

**Comment by hqro** [comment]
Works for me after resizing icons with 1:1 ratio.

**Comment by francocorreasosa** [comment]
A plenty of possible errors have been described here. The important thing is that this should be explicit in the builder output. So we don't have to guess what can be wrong.

**Comment by Inlesco** [comment]
@francocorreasosa exactly. And most of the errors mentioned here can even be caught before the actual build runs, you just need to run something, f.e., to gather all the paths of images in the repo, analyze them against the requirements (f.e., no images with alpha channel (no .png or similar), 1:1 image aspect ratio required, etc.).

I'm very surprised no solid solution has been produced for this... There's nothing worse than a horrifying developer experience when you have no control over identifying what's the cause of the error(s).

**Comment by terribleben** [comment]
@francocorreasosa and @Inlesco thanks for the feedback - we fully agree, and are internally working on (1) validating more of your project before the build, and (2) launching a way to view all build errors yourself. Sorry this is really annoying in the current state of affairs.

**Comment by iprastha** [comment]
+1 for more detailed error cause.
For me the first ios build after updating my app always produces this issue, then second build with -c flag will resolve it.
